# Change these first
owner: Source-Graphics-GmbH # Your GitHub username
repo: upptime # Your Github repository name

# Add your sites here
sites:
  - name: VoIP
    url: $VOIP_WEB
  - name: Sharing
    url: https://sharing.source-graphics.ch
  - name: Webmail for SG Services
    url: https://webmail.services.source-graphics.ch/
  - name: Gitlab
    url: https://gitlab.source-graphics.ch
  - name: FAQ
    url: https://faq.source-graphics.ch  
  - name: Marcel Web
    url: $MARCEL_WEB

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: Status Page of Source Graphics services
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
